module Colour

exception ColourException
type Colour =
  | RGB of float * float * float
  override rgb.ToString() =
    match rgb with
      RGB(r,g,b) -> "["+r.ToString()+","+g.ToString()+","+b.ToString()+"]"

let mkColour r g b = ...
let getR (RGB(r,_,_)) = ...
let getG (RGB(_,g,_)) = ...
let getB (RGB(_,_,b)) = ...
let scale (RGB(r,g,b)) s = ...
let merge w (RGB(r1,g1,b1)) (RGB(r2,g2,b2)) = ...
let toColor (RGB(r,g,b)) = ...
let fromColor (c:System.Drawing.Color) = ...

type Colour with
  static member ( + ) (RGB(r1,g1,b1),RGB(r2,g2,b2)) = ...
  static member ( * ) (RGB(r1,g1,b1),RGB(r2,g2,b2)) = ...
  static member ( * ) (s,c) = ...
