module Colour
exception ColourException
[<Sealed>]
type Colour =
  static member ( + ) : ...
  static member ( * ) : ...
  static member ( * ) : ...
  
val mkColour : ...
val getR : ...
val getG : ...
val getB : ...
val scale: ...
val merge : ...
val toColor : Colour -> System.Drawing.Color
val fromColor : System.Drawing.Color -> Colour
